### ISSUE TITLE
play-json 2.7.4

### ISSUE THREAD

**Issue by pjfanning** [gnieh/diffson#110]
Would it be possible to use play-json 2.7.4 as the dependent version for diffson 4.0.x until play-json 2.8.0 is released? The current code appears to compile and run ok with play-json 2.7.4. When the code is compiled with play-json 2.8.0-M4, it compiled code does not work with play-json 2.7.4.

**Comment by satabin** [comment]
Yes Play-json always introduce a lot of incompatibilities between minor versions. I can compile against 2.7.4 but I am not sure it makes a lot of sense. If you really want to use the current diffson milestone version with play-json 2.7.4, I would recommend you to depend only on diffson-core and copy the [two files](https://github.com/gnieh/diffson/tree/master/playJson/shared/src/main/scala/diffson/playJson) in your project to be compiled with your play-json version.

Please keep in mind that diffson 4 is still at a milestone stage and still subject to changes (especially if the underlying json library make breaking changes).

**Comment by pjfanning** [comment]
Thanks @satabin, I've already copied the 2 files into my project as you described. I can close this issue if you feel that it is best for diffson 4.0.0 to only work with play-json 2.8.

**Comment by satabin** [comment]
I would prefer, as diffson 4 is still a milestone version. I did it to align with all depending versions, which are mostly milestones preparing for 2.13 support.

**Comment by pjfanning** [comment]
https://github.com/pjfanning/diffson-play-json-sample
