### ISSUE TITLE
A way to serialize JsonPatch[_] to JSON

### ISSUE THREAD

**Issue by YanDoroshenko** [gnieh/diffson#158]
I'm looking for a way to serialize a JsonPatch[JsValue] to JSON. Is there a mechanism for that included in the library or should I handle it myself somehow? Thanks.

**Comment by satabin** [comment]
It depends on the JSON library you are using, see [here](https://github.com/gnieh/diffson#note-on-deserialization)? For the three libraries provided out of the box (circe, Play, and spray) there are encoders and decoders (or formats, or whatever the name is for this specific library), so if you import the diffson package for this library, you have them in scope. For instance for circe, you need

```scala
import diffson.circe._
```

**Comment by YanDoroshenko** [comment]
I tried it with PlayJson, but it said that it can't find format for a list of `Operation`s:
```
scala> implicit val fff: OFormat[JsonPatch[JsValue]] = Json.format
<console>:34: error: No instance of play.api.libs.json.Format is available for scala.collection.immutable.List[diffson.jsonpatch.Operation[play.api.libs.json.JsValue]] in the implicit scope (Hint: if declared in the same file, make sure it's declared before)
       implicit val fff: OFormat[JsonPatch[JsValue]] = Json.format
```

**Comment by satabin** [comment]
You probably didn't import the `DiffsonProtocol`:

```scala
import play.api.libs.json._
import diffson.playJson._
import diffson.playJson.DiffsonProtocol._
import diffson.jsonpatch._

val format = Json.format[JsonPatch[JsValue]]
```

**Comment by YanDoroshenko** [comment]
I didn't, but when I did it gave me a different error:
```
scala> val format = Json.format[JsonPatch[JsValue]]
<console>:26: error: _ must follow method; cannot follow (ops: List[diffson.jsonpatch.Operation[play.api.libs.json.JsValue]])(implicit evidence$8: diffson.Jsony[play.api.libs.json.JsValue])diffson.jsonpatch.JsonPatch[play.api.libs.json.JsValue] <and> (ops: diffson.jsonpatch.Operation[play.api.libs.json.JsValue]*)(implicit evidence$9: diffson.Jsony[play.api.libs.json.JsValue])diffson.jsonpatch.JsonPatch[play.api.libs.json.JsValue]
       val format = Json.format[JsonPatch[JsValue]]
```

**Comment by YanDoroshenko** [comment]
Tried serialization without explicitly creating a format for `JsonPatch`, everything works.
Maybe you can add an example for PlayJson to the README? Or I can do it.

**Comment by satabin** [comment]
I can put the imports in the README (will do it right away), but the rest is specific to the used json library, so I can only encourage people to refer to it.

**Comment by satabin** [comment]
Examples added: https://github.com/gnieh/diffson#note-on-deserialization
