### ISSUE TITLE
Release 4.1.0 depends on circe milestone version

### ISSUE THREAD

**Issue by anilkumarmyla** [gnieh/diffson#243]
https://github.com/gnieh/diffson/releases/tag/4.1.0
https://github.com/gnieh/diffson/compare/4.0.3...4.1.0 -> `val circeVersion = "0.14.0-M7"` 

I see that #241 already updated the version to a release version, but we'd need #242 to be ideally merged and then release diffson

**Comment by satabin** [comment]
I released it a few hours too early. I will release 4.1.1 later today with circe updated. Thanks for reporting.

**Comment by satabin** [comment]
I just released version 4.1.1 which depends on circe 0.14.1.

**Comment by anilkumarmyla** [comment]
thank you for the quick fix
