### ISSUE TITLE
[JsonPatch]: Array nested elements missing slashes in string representation

### ISSUE THREAD

**Issue by shell-software** [gnieh/diffson#30]
##### Sample
```scala
val source =
			"""[
			  | {
			  |     "a": 1
			  | }
			  |]""".stripMargin
val target =
			"""[
			  | {
			  |     "a": 2
			  | }
			  |]""".stripMargin
val patch = JsonDiff.diff(source, target, remember = false)
println(patch)
```

##### Actual:
```json
[ {
  "op" : "replace",
  "path" : "/0a",
  "value" : 2
} ]
```

##### Expected:
```json
[ {
  "op" : "replace",
  "path" : "/0/a",
  "value" : 2
} ]
```

**Comment by satabin** [comment]
Isn’t that the same problem as #29 ? If it is, please update to use the just released version 2.0.2

**Comment by shell-software** [comment]
Hi!

Thanks for quick reply

There is no version 2.0.2 yet in [Maven Repo](http://search.maven.org/#search%7Cga%7C1%7Cdiffson)
I used 2.0.1

I can download the sources and check if it is already fixed in master?

**Comment by satabin** [comment]
Sorry I made an error when publishing yesterday. It is now available in [sonatype repository](https://oss.sonatype.org/content/repositories/releases/org/gnieh/diffson_2.11/2.0.2/), and should be replicated to central within a few hours.

**Comment by shell-software** [comment]
Great, many thanks
