### ISSUE TITLE
Circe Support

### ISSUE THREAD

**Issue by emanresusername** [gnieh/diffson#33]
[![gif-keyboard-14795751616055203746](https://cloud.githubusercontent.com/assets/860471/19708441/5bc4dd6a-9ad3-11e6-92d1-e497a4d33481.gif)](https://github.com/travisbrown/circe)

**Comment by satabin** [comment]
I have never used circe, but I guess it can be done straight-forwardly. I was expecting a PR from @guersam, I don’t know if he already implemented it. Do you have a prototype for this implementation you can submit as PR?

**Comment by emanresusername** [comment]
i haven't dug in at all yet, but yeah, if nobody else has bitten before i get some free time, i can take a stab at it

**Comment by guersam** [comment]
Thanks for reminding. I have the implementation but couldn't open a PR due to other works while trying to rewrite the test suite to be generic enough for every supported JSON libs other than spray-json.

**Comment by emanresusername** [comment]
oh cool, i was about to start in on this, i'll hold off then
