### ISSUE TITLE
Scala 2.12 support plan

### ISSUE THREAD

**Issue by guersam** [gnieh/diffson#39]
There are two ways to support fresh Scala 2.12:

1. Wait until all of spray-json, play-json (and circe) for scala 2.12 is released
    - pros: requires no change
    - cons: we'll be blocked until play 2.6 is out

2. Split JSON dialects into dedicated submodules
    - pros: flexible and quick release, no more fragile 'provided' scope
    - cons: release process being complicated

3. Keep the single module structure and comment out missing dialects until released
    - pros: quick release with relatively simple process
    - cons: need to handle extra cross-building stuff like `scala-2.11` dir

which one do you prefer?

**Comment by satabin** [comment]
More modularity would allow for quicker releases for dependencies that have quicker life-cycle. Using sbt submodules, this will be easy. I will refactor the sources to extract dialects to their own modules.
I’ll do it this week.

**Comment by guersam** [comment]
Sounds great, thanks!
