### ISSUE TITLE
Add patch inversion

### ISSUE THREAD

**Issue by satabin** [gnieh/diffson#47]
Patches may be inverted if they respect some constraints (e.g. if old values are remembered upon deletion and modification). I would be great to have the inversion operation integrated in Diffson with explanation when it cannot be inverted.

**Comment by fancywriter** [comment]
What does specification says (if it does) for "test" and "copy" operation? How to inverse them?

**Comment by satabin** [comment]
RFC does nothing about inversion, because their operations are not invertible. `test` is the same when inverted, it does not change any value. For `copy` the problem is similar to inverting a `remove` and an `add` (or `replace`).

Patches per se are not invertible, they can be if the diff algorithm that produces them respect some constraints and the _inverted_ patch is applied to the right context. Before this one is possible, I wanted to check the state of the art and define constraints in our specific context.

**Comment by fancywriter** [comment]
For *add*, *remove* and *replace* it should be quite easy - if old value is saved, invert is possible. However, for *copy* (and probably *move*) it is not as easy, because they don't even have a place where to store old value.

**Comment by satabin** [comment]
The fact that `add`, `remove` and `replace` save the old value is an extension specific to diffson, not present in the RFC. Because the current diff implementation in diffson never generates `copy` or `move` operations, I never added the old value to these operations. As I said, patch inversion is not an easy problem, depending on existing operations, their shape, and how patches are generated.
