### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by fancywriter** [gnieh/diffson#57]
There is a need to add performance tests for big datasets to compare different algorithms (currently there are two of them "out of the box": patience and dynamic programming.
I can add them, but I am not sure where is the best place to place them - separate project inside this repository, or inside `./src/it/scala/` directory in playJson/sprayJson/circe subprojects for every implementation (implemented on scalatest)? If separate project, is it integration test in `./src/it/scala/` or three main objects in `./src/main/scala/`?

**Comment by satabin** [comment]
To benchmark algorithms, I would create a `benchmark` project using [scalameter](https://scalameter.github.io/). If your goal is to benchmark the diff algorithm itself and nothing related to the specific context of Json, I eventually plan to move to [tekstlib](https://github.com/gnieh/tekstlib) for this, so I would prefer benchmarks to go there.

**Comment by fancywriter** [comment]
Oh, interesting. Are you going to reuse tekstlib as a dependency for diffson in future?
Right now I need to benchmark specific JSON algorithm (I faced issue in real life with few megabytes size datasets, speed differs dramatically), though it's probably not so different.

**Comment by satabin** [comment]
Yes that’s the plan because LCS algorithms are also implemented there and I want to avoid duplicating such implementation. You can start implementing the benchmark here and I’ll move it to tekstlib later if it makes sense.

**Comment by fancywriter** [comment]
I added benchmarks there https://github.com/gnieh/tekstlib/pull/14
I think it will be fair enough to have them there, not here, benchmarks explicitly shows that dynamic algorithm could be better. Specific JSON implementation probably is not important here, we deal with sequences anyway...

Do you need any assistance in replacing Lcs.* classes in this project with **tekstlib** as a dependency?

**Comment by satabin** [comment]
I have a branch on my computer but a severe regression in the patience implementation. I had no time lately to investigate further. I pushed the current branch name `diff/extended-format` (the goal is to extend diff format to be able to generate diffs from strings as for arrays).

**Comment by fancywriter** [comment]
I have noticed that JSON patch in **TestSerialization.a patch should be applicable to a serializable Scala object if the shape is kept** is different. For old implemenation
```
Patch [ {
  "op" : "replace",
  "path" : "/a",
  "value" : 10
}, {
  "op" : "replace",
  "path" : "/b",
  "value" : false
}, {
  "op" : "replace",
  "path" : "/c",
  "value" : "toto"
}, {
  "op" : "add",
  "path" : "/d/2",
  "value" : 3
}, {
  "op" : "add",
  "path" : "/d/-",
  "value" : 5
} ]
```

For the new 
```
Patch [ {
  "op" : "replace",
  "path" : "/a",
  "value" : 10
}, {
  "op" : "replace",
  "path" : "/b",
  "value" : false
}, {
  "op" : "replace",
  "path" : "/c",
  "value" : "toto"
}, {
  "op" : "add",
  "path" : "/d/2",
  "value" : 3
}, {
  "op" : "add",
  "path" : "/d/5",
  "value" : 5
} ]
```

Last **add** path is different, was `/d/-`, became `/d/5`, which causes index out of bound, because array has size = 4 at this moment...

**Comment by satabin** [comment]
I will try to work on this this weekend, thanks for reporting.

**Comment by satabin** [comment]
This problem should now be fixed by new commit on the `diff/extended-patch` branch. It was a case I mishandled when generating `Add` commands for arrays. Now it should work.
