### ISSUE TITLE
issues with play! 2.3.8

### ISSUE THREAD

**Issue by asheshambasta** [gnieh/diffson#60]
I'm trying to use this with Play! 2.3.8 and I've been seeing several issues with compilations.
```
"org.gnieh" % "diffson-play-json_2.11" % "2.2.1" // added to libraryDependencies
```

And I see errors that are:
```
play.PlayExceptions$CompilationException: Compilation error[object ValidationError is not a member of package play.api.data.validation]
```

`scalaVersion := "2.11.7"`

Is there some sort of documentation on the versions of `play-json` this library is compatible with?

**Comment by satabin** [comment]
Diffson depends on play-json 2.6.0.
I am not aware of the compatibility between different versions of Play! but I seem to recall that there were API changes in play-json 2.6.0. Maybe refer to the Play! documentation for such compatibility issues.

**Comment by asheshambasta** [comment]
Okay, thanks for clarifying @satabin. I'll dig into this a bit deeper and let you know if I find something. Closing this for now.
