### ISSUE TITLE
LowPriorityWrites.traversableWrites does not preserve order

### ISSUE THREAD

**Issue by t3hnar** [gnieh/diffson#62]
I found that `LowPriorityWrites.traversableWrites` does not preserve the order. 
For instance we have `SortedSet` of elements, however json has wrong output because of 
`JsArray(as.map(w.writes(_)).toArray[JsValue])`

**Comment by satabin** [comment]
For the record (and explain why @t3hnar closed it right after opening here), this is actually a bug in Play!, opened  by the the author here: playframework/playframework#7750

**Comment by t3hnar** [comment]
yes, I somehow missed the repo while firing the issue. sorry for disturbance :)

**Comment by satabin** [comment]
No problem, I just commented for whoever might come across this bug :)
