### ISSUE TITLE
Feature request: please cross-compile to Scala.JS

### ISSUE THREAD

**Issue by japgolly** [gnieh/diffson#86]

**Comment by satabin** [comment]
That's a good idea, I will work on that. Thanks for the suggestion.

**Comment by japgolly** [comment]
Awesome, thank you! I originally just wanted to just do it and submit a PR but I just don't have the time. I know it's not the same but instead I'd be happy to do a review if you'd like :)

**Comment by satabin** [comment]
Don't worry, I am happy to do it :) And someone asked me if he could have a take on it, already. Do you need this feature urgently?

**Comment by japgolly** [comment]
That's great!

> Do you need this feature urgently?

I think I'm going to need it in a week, maybe two. If this is still open then I find I'll have much more ability by necessity to contribute :smile:

**Comment by satabin** [comment]
Version 4.0.0-M2 is now published with support for Scala.JS

**Comment by japgolly** [comment]
Wow awesome, thank you so much for this!

**Comment by japgolly** [comment]
I needed this today and was able to use it flawlessly. Just wanted to say thanks again! I appreciate it!

**Comment by satabin** [comment]
Thanks, nice to hear. If everything works properly over the next week or so, I will release 4.0.0 for good :)
